name: resumecorgi.com

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4

      - name: Cache Dependencies
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-

      - name: Build
        shell: pwsh
        run: |
          npm ci
          npm run test
          npm run build

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: resumecorgi.com
          path: dist/

  deploy-cloudflare:
    needs: [ build ]
    runs-on: ubuntu-latest
    name: Deploy (Cloudflare)
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: resumecorgi.com
          path: dist/

      - name: Deploy to Cloudflare
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy dist/ --project-name=resumecorgi

  deploy-azure:
    needs: [ build ]
    runs-on: ubuntu-latest
    name: Deploy (Azure)
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: resumecorgi.com
          path: dist/

      - name: Deploy to Azure Static Web Apps
        id: deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_RED_MOSS_08B6A040F }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "dist"
          api_location: ""
          output_location: ""
          skip_app_build: true
          skip_api_build: true