name: Deploy (Cloudflare)

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    name: Publish
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4

      - name: Build
        shell: pwsh
        run: |
          npm ci
          npm run test
          npm run build

      - name: Save Artifact
        uses: actions/upload-artifact@v4
        with:
          name: resumecorgi.com
          path: dist/

      - name: Deploy to Cloudflare
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy dist/ --project-name=resumecorgi.com